package http_error

const (
	MustHaveOnlyOneSheet       = "O excel deve ter apenas uma página."
	Unexpected                 = "Ocorreu um erro inesperado."
	Forbidden                  = "Credenciais inválidas"
	LoginCannotBeEmpty         = "CPF ou Email não pode ser vazio."
	CNPJInvalid                = "CNPJ é inválido."
	EmptyPasswordField         = "Senha vazia."
	InvalidParameter           = "Parâmetro inválido."
	UserNotFound               = "Usuário não encontrado"
	UserDeleted                = "Usuário excluído."
	UserInactivated            = "Usuário inativo."
	EmptyNameFieldError        = "Campo de nome vazio."
	EmailExistError            = "E-mail já está sendo usado."
	EmptyEmailFieldError       = "E-mail não pode ser vazio."
	DocumentExistError         = "CPF já está sendo usado."
	DocumentNotValid           = "CPF não é valido."
	EmptyDocumentFieldError    = "CPF vazio."
	InvalidEmailFieldError     = "E-mail inválido."
	PasswordIsntValid          = "Senha inválida."
	PasswordDoesntMatch        = "A senha não confere."
	InvalidRequestBody         = "Corpo da requisição não é válido."
	InvalidCertificate         = "certificado inválido."
	InvalidEquipment           = "Equipamento inválido."
	Unauthorized               = "Você não tem permissão para acessar esse recurso."
	EmptyURLFieldError         = "URL não pode ser vazio."
	EmptyImageError            = "Imagem não pode ser vazia."
	EmptyCertificateFieldError = "Nome do certificado não pode ser vazio."
	CertificateNotFound        = "certificado não encontrado."
	InvalidMetadata            = "Metadata inválida."
	InvalidImageExtension      = "Extensão de imagem inválida."
	EquipmentNotFound          = "Equipamento não encontrado."
	EmptyEquipmentFieldError   = "Nome do equipamento não pode ser vazio."
	CertificateIDEmpty         = "certificado não pode ser vazio."
)
